# SAM configuration for Staging environment
# Deploy with: sam deploy --config-file samconfig-staging.toml

version = 0.1

[default.global.parameters]
stack_name = "user-service-staging"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
region = "us-east-1"
s3_bucket = "anecdotario-sam-artifacts-staging-us-east-1"
parameter_overrides = [
    "Environment=staging",
    "TableName=Users-staging",
    "ParameterStorePrefix=/anecdotario/staging/user-service",
]
tags = [
    "Environment=staging",
    "Service=user-service",
    "Owner=qa-team"
]

[default.package.parameters]
s3_bucket = "anecdotario-sam-artifacts-staging-us-east-1"

[default.sync.parameters]
watch = false

[default.local_start_api.parameters]
warm_containers = "LAZY"
parameter_overrides = [
    "Environment=staging",
    "TableName=Users-staging",
    "ParameterStorePrefix=/anecdotario/staging/user-service",
]

[default.local_start_lambda.parameters]
warm_containers = "LAZY"
parameter_overrides = [
    "Environment=staging",
    "TableName=Users-staging",
    "ParameterStorePrefix=/anecdotario/staging/user-service",
]