# SAM configuration for Development environment
# Deploy with: sam deploy --config-file samconfig-dev.toml

version = 0.1

[default.global.parameters]
stack_name = "user-service-dev"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
region = "us-east-1"
s3_bucket = "anecdotario-sam-artifacts-us-east-1"
parameter_overrides = [
    "Environment=dev",
    "TableName=Users-dev",
    "ParameterStorePrefix=/anecdotario/dev/user-service",
    "CommonsPhotoUploadFunction=commons-service-dev-PhotoUploadFunction"
]
tags = [
    "Environment=dev",
    "Service=user-service",
    "Owner=development-team"
]

[default.package.parameters]
s3_bucket = "anecdotario-sam-artifacts-us-east-1"

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"
parameter_overrides = [
    "Environment=dev",
    "TableName=Users-dev",
    "ParameterStorePrefix=/anecdotario/dev/user-service",
    "CommonsPhotoUploadFunction=commons-service-dev-PhotoUploadFunction"
]

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
parameter_overrides = [
    "Environment=dev", 
    "TableName=Users-dev"
]