# SAM configuration for Development environment
# Deploy with: sam deploy --config-file samconfig-dev.toml

version = 0.1

[default.global.parameters]
stack_name = "user-service-dev"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = [
    "Environment=dev",
    "TableName=Users-dev"
]
tags = [
    "Environment=dev",
    "Service=user-service",
    "Owner=development-team"
]

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"
parameter_overrides = [
    "Environment=dev",
    "TableName=Users-dev"
]

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
parameter_overrides = [
    "Environment=dev", 
    "TableName=Users-dev"
]