AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  user-service

  Anecdotario User Service - Manages user accounts, authentication, and certification

Parameters:
  Environment:
    Type: String
    Description: Environment name (dev, staging, prod)
    AllowedValues: [dev, staging, prod]
    Default: dev
  
  TableName:
    Type: String
    Description: DynamoDB table name for users
    Default: "Users-dev"
  
  MaxImageSize:
    Type: Number
    Description: Maximum image size in bytes
    Default: "5242880"  # 5MB
  
  ParameterStorePrefix:
    Type: String
    Description: Parameter Store prefix for configuration values
    Default: "/anecdotario/dev/user-service"
  

Conditions:
  IsDevEnvironment: !Equals [!Ref Environment, dev]
  IsProdEnvironment: !Equals [!Ref Environment, prod]

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30  # Increased for image processing
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        USER_TABLE_NAME: !Ref UserTable
        PHOTO_BUCKET_NAME: !Ref PhotoBucket
        MAX_IMAGE_SIZE: !Ref MaxImageSize
        PARAMETER_STORE_PREFIX: !Ref ParameterStorePrefix

Resources:
  # API Gateway with JWT Authorizer and OpenAPI Documentation
  UserServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${AWS::StackName}-api"
      StageName: Prod
      Cors:
        AllowOrigin: !If 
          - IsDevEnvironment
          - "'*'"
          - !Sub "'https://${Environment}.anecdotario.com,https://anecdotario.com'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'GET,POST,DELETE,OPTIONS'"
        AllowCredentials: false
        MaxAge: "'600'"
      Auth:
        DefaultAuthorizer: CognitoJWTAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false  # Don't require auth for OPTIONS
        Authorizers:
          CognitoJWTAuthorizer:
            Type: COGNITO_USER_POOLS
            UserPoolArn: !Sub 
              - "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/{{resolve:ssm:/anecdotario/${EnvironmentName}/cognito/user-pool-id}}"
              - EnvironmentName: !If 
                  - IsDevEnvironment
                  - development
                  - !If 
                    - IsProdEnvironment
                    - production
                    - !Ref Environment
            Identity:
              Header: Authorization
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: !If 
                - IsDevEnvironment
                - "'*'"
                - !Sub "'https://${Environment}.anecdotario.com,https://anecdotario.com'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              Access-Control-Allow-Methods: "'GET,POST,DELETE,OPTIONS'"
              Access-Control-Allow-Credentials: "'false'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: !If 
                - IsDevEnvironment
                - "'*'"
                - !Sub "'https://${Environment}.anecdotario.com,https://anecdotario.com'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              Access-Control-Allow-Methods: "'GET,POST,DELETE,OPTIONS'"
              Access-Control-Allow-Credentials: "'false'"
  PhotoUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: photo-upload/app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      MemorySize: 512  # Increased for image processing
      Timeout: 60      # Extended timeout for image processing + S3 cleanup
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
        - S3CrudPolicy:
            BucketName: !Ref PhotoBucket
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:GetParametersByPath
            Resource: 
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${ParameterStorePrefix}/*"
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/anecdotario/${Environment}/cognito/*"
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: 
              - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:anecdotario-commons-photo-upload-${Environment}"
      Events:
        PhotoUpload:
          Type: Api
          Properties:
            RestApiId: !Ref UserServiceApi
            Path: /users/{userId}/photo
            Method: post
            Auth:
              Authorizer: CognitoJWTAuthorizer

  PhotoDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: photo-delete/app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      MemorySize: 256  # Medium memory for S3 operations
      Timeout: 30      # Longer timeout for multiple S3 deletions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
        - S3CrudPolicy:
            BucketName: !Ref PhotoBucket
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:GetParametersByPath
            Resource: 
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${ParameterStorePrefix}/*"
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/anecdotario/${Environment}/cognito/*"
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: 
              - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:anecdotario-commons-photo-delete-${Environment}"
      Events:
        PhotoDelete:
          Type: Api
          Properties:
            RestApiId: !Ref UserServiceApi
            Path: /users/{userId}/photo
            Method: delete
            Auth:
              Authorizer: CognitoJWTAuthorizer

  PhotoRefreshFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: photo-refresh/app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      MemorySize: 128  # Minimal memory for URL generation
      Timeout: 10      # Short timeout for presigned URL generation
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UserTable
        - S3ReadPolicy:
            BucketName: !Ref PhotoBucket
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:GetParametersByPath
            Resource: 
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${ParameterStorePrefix}/*"
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/anecdotario/${Environment}/cognito/*"
      Events:
        PhotoRefresh:
          Type: Api
          Properties:
            RestApiId: !Ref UserServiceApi
            Path: /users/{userId}/photo/refresh
            Method: get
            Auth:
              Authorizer: CognitoJWTAuthorizer

  UserLookupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: user-lookup/app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      MemorySize: 128  # Minimal memory for read operations
      Timeout: 5       # Short timeout for simple queries
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UserTable
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:GetParametersByPath
            Resource: 
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${ParameterStorePrefix}/*"
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/anecdotario/${Environment}/cognito/*"
      Events:
        GetUserByNickname:
          Type: Api
          Properties:
            RestApiId: !Ref UserServiceApi
            Path: /users/by-nickname/{nickname}
            Method: get
            Auth:
              Authorizer: CognitoJWTAuthorizer

  NicknameValidateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: nickname-validate/app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      MemorySize: 128  # Minimal memory for validation calls
      Timeout: 10      # Reasonable timeout for commons service calls
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:GetParametersByPath
            Resource: 
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${ParameterStorePrefix}/*"
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/anecdotario/${Environment}/cognito/*"
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: 
              - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:anecdotario-nickname-validate-${Environment}"
      Events:
        ValidateNickname:
          Type: Api
          Properties:
            RestApiId: !Ref UserServiceApi
            Path: /users/validate-nickname/{nickname}
            Method: get
            Auth:
              Authorizer: NONE  # Anonymous access for registration flow

  UserCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: user-create/app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      MemorySize: 128  # Minimal memory for write operations
      Timeout: 10      # Slightly longer timeout for database writes
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:GetParametersByPath
            Resource: 
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${ParameterStorePrefix}/*"
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/anecdotario/${Environment}/cognito/*"
      Events:
        CreateUser:
          Type: Api
          Properties:
            RestApiId: !Ref UserServiceApi
            Path: /users
            Method: post
            Auth:
              Authorizer: CognitoJWTAuthorizer

  UserDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: user-delete/app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      MemorySize: 256  # More memory for S3 operations
      Timeout: 30      # Longer timeout for photo cleanup
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
        - S3CrudPolicy:
            BucketName: !Ref PhotoBucket
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:GetParametersByPath
            Resource: 
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${ParameterStorePrefix}/*"
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/anecdotario/${Environment}/cognito/*"
      Events:
        DeleteUserSelf:
          Type: Api
          Properties:
            RestApiId: !Ref UserServiceApi
            Path: /users
            Method: delete
            Auth:
              Authorizer: CognitoJWTAuthorizer
        DeleteUserById:
          Type: Api
          Properties:
            RestApiId: !Ref UserServiceApi
            Path: /users/{userId}
            Method: delete
            Auth:
              Authorizer: CognitoJWTAuthorizer

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: cognito_id
          AttributeType: S
        - AttributeName: nickname
          AttributeType: S
      KeySchema:
        - AttributeName: cognito_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: nickname-index
          KeySchema:
            - AttributeName: nickname
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: user-service

  PhotoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-photos-${Environment}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldPhotos
            Status: Enabled
            ExpirationInDays: 365
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: user-service

  PhotoBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PhotoBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadThumbnailsOnly
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${PhotoBucket}/users/*/thumbnail_*"

Outputs:
  # API Gateway endpoint
  UserServiceApiEndpoint:
    Description: "API Gateway endpoint URL for environment stage"
    Value: !Sub "https://${UserServiceApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiEndpoint"
  
  # Lambda functions
  PhotoUploadFunction:
    Description: "Photo Upload Lambda Function ARN"
    Value: !GetAtt PhotoUploadFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-PhotoUploadFunctionArn"
  
  PhotoDeleteFunction:
    Description: "Photo Delete Lambda Function ARN"
    Value: !GetAtt PhotoDeleteFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-PhotoDeleteFunctionArn"
  
  PhotoRefreshFunction:
    Description: "Photo Refresh Lambda Function ARN"
    Value: !GetAtt PhotoRefreshFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-PhotoRefreshFunctionArn"
  
  UserLookupFunction:
    Description: "User Lookup Lambda Function ARN"
    Value: !GetAtt UserLookupFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-UserLookupFunctionArn"
  
  UserCreateFunction:
    Description: "User Create Lambda Function ARN"
    Value: !GetAtt UserCreateFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-UserCreateFunctionArn"
  
  UserDeleteFunction:
    Description: "User Delete Lambda Function ARN"
    Value: !GetAtt UserDeleteFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-UserDeleteFunctionArn"
  
  # S3 Bucket
  PhotoBucket:
    Description: "S3 bucket for user photos"
    Value: !Ref PhotoBucket
    Export:
      Name: !Sub "${AWS::StackName}-PhotoBucket"
  
  # DynamoDB table
  UserTable:
    Description: "DynamoDB table for users"
    Value: !Ref UserTable
    Export:
      Name: !Sub "${AWS::StackName}-UserTable"
  
  # Environment
  Environment:
    Description: "Deployment environment"
    Value: !Ref Environment
    Export:
      Name: !Sub "${AWS::StackName}-Environment"
