version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install aws-sam-cli
      - pip install pytest pytest-cov
      
  pre_build:
    commands:
      - echo "Running tests..."
      - |
        # Test all Lambda functions
        for function in photo-upload user-create user-delete user-lookup; do
          echo "Testing $function..."
          cd $function
          pip install -r requirements.txt
          python -m pytest tests/ -v --cov=app --cov-report=term-missing
          cd ..
        done
      
  build:
    commands:
      - echo "Building SAM application..."
      - sam build --use-container
      
  post_build:
    commands:
      - echo "Packaging SAM application..."
      - |
        sam package \
          --s3-bucket $ARTIFACTS_BUCKET \
          --s3-prefix $CODEBUILD_BUILD_ID \
          --output-template-file packaged-template.yaml

artifacts:
  files:
    - packaged-template.yaml
    - samconfig-*.toml