version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install aws-sam-cli
      - pip install pytest pytest-cov
      
  pre_build:
    commands:
      - echo "Creating SAM artifact buckets..."
      - |
        # Create SAM artifact buckets for each environment if they don't exist
        BUCKETS=(
          "anecdotario-sam-artifacts-us-east-1"
          "anecdotario-sam-artifacts-staging-us-east-1"
          "anecdotario-sam-artifacts-prod-us-east-1"
        )
        
        for bucket in "${BUCKETS[@]}"; do
          echo "Checking if bucket $bucket exists..."
          if aws s3 ls "s3://$bucket" 2>&1 | grep -q 'NoSuchBucket\|does not exist'; then
            echo "Creating bucket $bucket..."
            aws s3 mb "s3://$bucket" --region us-east-1
            aws s3api put-bucket-encryption \
              --bucket "$bucket" \
              --server-side-encryption-configuration '{
                "Rules": [
                  {
                    "ApplyServerSideEncryptionByDefault": {
                      "SSEAlgorithm": "AES256"
                    }
                  }
                ]
              }'
            aws s3api put-bucket-versioning \
              --bucket "$bucket" \
              --versioning-configuration Status=Enabled
            echo "Bucket $bucket created successfully"
          else
            echo "Bucket $bucket already exists"
          fi
        done
      - echo "Running tests..."
      - |
        # Test all Lambda functions
        for function in photo-upload user-create user-delete user-lookup; do
          echo "Testing $function..."
          cd $function
          pip install -r requirements.txt
          python -m pytest tests/ -v --cov=app --cov-report=term-missing
          cd ..
        done
      
  build:
    commands:
      - echo "Building SAM application..."
      - sam build --use-container
      
  post_build:
    commands:
      - echo "Packaging SAM application..."
      - |
        sam package \
          --s3-bucket $ARTIFACTS_BUCKET \
          --s3-prefix $CODEBUILD_BUILD_ID \
          --output-template-file packaged-template.yaml

artifacts:
  files:
    - packaged-template.yaml
    - samconfig-*.toml
    - pipeline/deploy-*-buildspec.yml