version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - sam deploy --config-file samconfig-staging.toml --no-confirm-changeset --no-fail-on-empty-changeset --template-file packaged-template.yaml